name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.eduxiji.net/carbon/lrv-rust-bl"
      env:
        GITLAB_HOSTNAME: "gitlab.eduxiji.net"
        GITLAB_USERNAME: "carbon"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "1309"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
